export const DOG_BREEDS = [
  'Indie / Pariah',
  'Labrador Retriever',
  'Golden Retriever',
  'German Shepherd',
  'Beagle',
  'Pug',
  'Shih Tzu',
  'Doberman Pinscher',
  'Rottweiler',
  'Boxer',
  'Dachshund',
  'Great Dane',
  'Siberian Husky',
  'Alaskan Malamute',
  'Cocker Spaniel',
  'English Cocker Spaniel',
  'American Cocker Spaniel',
  'Bulldog',
  'French Bulldog',
  'Pomeranian',
  'Chihuahua',
  'Maltese',
  'Lhasa Apso',
  'Saint Bernard',
  'Bernese Mountain Dog',
  'Border Collie',
  'Australian Shepherd',
  'Australian Cattle Dog',
  'Collie',
  'Shetland Sheepdog',
  'Bull Terrier',
  'Staffordshire Bull Terrier',
  'American Staffordshire Terrier',
  'Pit Bull Terrier',
  'Miniature Schnauzer',
  'Giant Schnauzer',
  'Standard Schnauzer',
  'Yorkshire Terrier',
  'Jack Russell Terrier',
  'West Highland White Terrier',
  'Cavalier King Charles Spaniel',
  'Basset Hound',
  'Bloodhound',
  'Bichon Frise',
  'Akita',
  'Shiba Inu',
  'Chow Chow',
  'Dalmatian',
  'Greyhound',
  'Whippet',
  'Great Pyrenees',
  'Newfoundland',
  'Samoyed',
  'Irish Setter',
  'English Setter',
  'Pointer',
  'Vizsla',
  'Weimaraner',
  'Poodle (Toy)',
  'Poodle (Miniature)',
  'Poodle (Standard)',
  'Labradoodle',
  'Goldendoodle',
  'Cane Corso',
  'Belgian Malinois',
  'Old English Sheepdog',
  'Pekingese',
  'Papillon',
  'Basenji',
  'Borzoi',
  'Havanese',
  'Shar Pei',
  'Tibetan Mastiff',
  'Tibetan Terrier',
  'Indian Spitz',
  'Rajapalayam',
  'Mudhol Hound',
  'Chippiparai',
  'Kombai',
  'Bakharwal Dog',
  'Rampur Greyhound',
  'Gaddi Kutta',
  'Kanni',
  'Himalayan Sheepdog',
  'Indian Mastiff'
];

export const CAT_BREEDS = [
  'Indie Cat',
  'Persian',
  'Maine Coon',
  'Ragdoll',
  'Siamese',
  'British Shorthair',
  'Abyssinian',
  'Bengal',
  'Birman',
  'Bombay',
  'Burmese',
  'Chartreux',
  'Devon Rex',
  'Sphynx',
  'Himalayan',
  'Norwegian Forest',
  'Oriental',
  'Russian Blue',
  'Scottish Fold',
  'Munchkin',
  'American Shorthair',
  'American Curl',
  'Balinese',
  'Cornish Rex',
  'Egyptian Mau',
  'Exotic Shorthair',
  'Havana Brown',
  'Korat',
  'LaPerm',
  'Manx',
  'Ocicat',
  'Ragamuffin',
  'Savannah',
  'Singapura',
  'Somali',
  'Tonkinese',
  'Turkish Angora',
  'Turkish Van'
];

export const OTHER_BREEDS = [
  'Rabbit (Domestic)',
  'Guinea Pig',
  'Hamster',
  'Parrot',
  'Budgerigar',
  'Lovebird',
  'Cockatiel',
  'Tortoise',
  'Turtle',
  'Other / Not listed'
];

export const PET_TYPES = ['Dog', 'Cat', 'Other'] as const;
export type PetType = typeof PET_TYPES[number];

export const INDIAN_CITIES = [
  'Agartala',
  'Agra',
  'Ahmedabad',
  'Aizawl',
  'Ajmer',
  'Akola',
  'Aligarh',
  'Allahabad',
  'Alwar',
  'Amravati',
  'Amritsar',
  'Anand',
  'Asansol',
  'Aurangabad',
  'Ayodhya',
  'Bangalore',
  'Bengaluru',
  'Bareilly',
  'Bathinda',
  'Belgaum',
  'Bellary',
  'Bharatpur',
  'Bhilai',
  'Bhilwara',
  'Bhiwandi',
  'Bhopal',
  'Bhubaneswar',
  'Bhuj',
  'Bikaner',
  'Bilaspur',
  'Bokaro',
  'Chandigarh',
  'Chandrapur',
  'Chennai',
  'Coimbatore',
  'Cuttack',
  'Dehradun',
  'Delhi',
  'Dhanbad',
  'Durg',
  'Erode',
  'Faridabad',
  'Firozabad',
  'Gandhinagar',
  'Gaya',
  'Ghaziabad',
  'Gorakhpur',
  'Gulbarga',
  'Guntur',
  'Gurgaon',
  'Gurugram',
  'Guwahati',
  'Gwalior',
  'Haldwani',
  'Hisar',
  'Hosur',
  'Howrah',
  'Hubli',
  'Hubli-Dharwad',
  'Hyderabad',
  'Imphal',
  'Indore',
  'Jabalpur',
  'Jaipur',
  'Jalandhar',
  'Jalgaon',
  'Jalpaiguri',
  'Jammu',
  'Jamnagar',
  'Jamshedpur',
  'Jhansi',
  'Jodhpur',
  'Jorhat',
  'Kadapa',
  'Kakinada',
  'Kalaburagi',
  'Kalyan-Dombivli',
  'Kancheepuram',
  'Kannur',
  'Kanpur',
  'Karnal',
  'Kharagpur',
  'Kochi',
  'Kolhapur',
  'Kolkata',
  'Kollam',
  'Korba',
  'Kota',
  'Kozhikode',
  'Kurnool',
  'Kurukshetra',
  'Lucknow',
  'Ludhiana',
  'Madurai',
  'Mangalore',
  'Mathura',
  'Meerut',
  'Moradabad',
  'Muzaffarpur',
  'Mysore',
  'Nagpur',
  'Nanded',
  'Nashik',
  'Navi Mumbai',
  'Nellore',
  'Noida',
  'Panaji',
  'Panipat',
  'Patiala',
  'Patna',
  'Pimpri-Chinchwad',
  'Pondicherry',
  'Puducherry',
  'Pune',
  'Raipur',
  'Rajahmundry',
  'Rajkot',
  'Rampur',
  'Ranchi',
  'Rewa',
  'Rourkela',
  'Salem',
  'Sambalpur',
  'Sangli',
  'Shimla',
  'Siliguri',
  'Solapur',
  'Srinagar',
  'Surat',
  'Thane',
  'Thiruvananthapuram',
  'Thrissur',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tiruppur',
  'Udaipur',
  'Ujjain',
  'Vadodara',
  'Varanasi',
  'Vasai-Virar',
  'Vellore',
  'Vijayawada',
  'Visakhapatnam',
  'Warangal'
];
